### ISSUE TITLE
How to not justify labels

### ISSUE THREAD

**Issue by theclue** [andrie/ggdendro#19]
Hi,

tnx for this great package. It's really a life-saver for whom, like me, which need to code additional informations (ie colors) in thier trees.

Ssometimes, for clarity, it could be useful to not justify labels and have something similar to plot(hclust(blahblabh)) output, ie:

![image](https://cloud.githubusercontent.com/assets/1724406/11035871/53538958-86f5-11e5-8cea-354d5297795f.png)

I could probably do that manually handling the segment portion of the object, but it's probably a pain in the neck. so I'm wondering if it could be a nice feature to add for the package...

tnx for your time and have a nice day,
gabriele

**Comment by talgalili** [comment]
Dear Gabriele, 
As far as I know (and Andrie, please correct me if I am mistaken), this is not possible in ggdendro. This is due to the way it handles the plotting of labels.
However, it is possible using ggdend (a modified ggdendro within the R package dendextend).

Look at this:
https://cran.r-project.org/web/packages/dendextend/vignettes/introduction.html#ggplot2-integration
And first use the function
dendextend::hang.dendrogram
on your dendrogram.
