### ISSUE TITLE
dendro_data error for rpart

### ISSUE THREAD

**Issue by lpfgarcia** [andrie/ggdendro#20]
Dear,

I'm trying to run the exactly example code about `rpart`  from the Vignette and had this error in the function `dendro_data()`:

```
model <- rpart(Kyphosis ~ Age + Number + Start,  method = "class", data = kyphosis)
ddata <- dendro_data(model)

Error in rpartco(x) : 
  no information available on parameters from previous call to plot()
```
 
Do you know what is the problem?

Regards,
Luis

**Comment by andrie** [comment]
Interesting, thanks for the report.

This happens when you don't load the `rpart` package.

Try this to make the problem go away.

```r
library(ggdendro)
library(rpart)

model <- rpart(Kyphosis ~ Age + Number + Start, method = "class", data = kyphosis)
ddata <- dendro_data(model)
```

**Comment by andrie** [comment]
To do:

* Update example to load the `rpart` package

**Comment by lpfgarcia** [comment]
Hi Andrie,

The problem is intermittent:

R version 3.2.2 (2015-08-14) -- "Fire Safety"
Copyright (C) 2015 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library(rpart)
> library(ggdendro)
> model <- rpart(Kyphosis ~ Age + Number + Start, method = "class", data = kyphosis)
> ddata <- dendro_data(model)
Error in rpartco(x) : 
  no information available on parameters from previous call to plot()
> model <- rpart(Kyphosis ~ Age + Number + Start, method = "class", data = kyphosis)
> ddata <- dendro_data(model)

**Comment by DanielaVasco** [comment]
Hi Andrie,

I think the problem is in the function text.rpart().
This function calls the function rpartco(), just with the parameter x.
As the parms entry is missing, the error message is sent.
I don't know why this error is intermittent, but when I put a default parms vector in the function text.rpart() the error message stopped when I called the function dendro_data.rpart.
So it seems to be the problem.

If you could check that in the code of the package, it would be great!

Kind regards,

DanielaV

**Comment by andrie** [comment]
Thank you. This information was helpful.

I have traced the problem to the following:

1. `rpart::plot.rpart()` computes the plotting data for each plot device separately
2. It does this by saving the plot parameters in an object, referred to as `parms` in an environment, but the name of this object also contains the name of the `dev.cur()`
3. the error happens in a fresh session, when `plot()` has not been called before.

This reproduces the problem:

```r
library(rpart)
library(ggdendro)
model <- rpart(Kyphosis ~ Age + Number + Start,  method = "class", data = kyphosis)
ddata <- dendro_data(model)

plot.new()
ddata <- dendro_data(model)
```

Since the whole point of `ggdendro` is to compute the data independent of the plotting device, I have fixed this by explicitly passing `parms` where it is needed.

**Comment by DanielaVasco** [comment]
Hi Andrie,

Thank you very much for fixing that and for your package.
It has been really helpful for what I am doing.

Do you think it is possible to not open a new device when the function dendro_data() is called.
I have it in a loop and it opens several devices.

Thanks again.

Kind regards,
Daniela

**Comment by andrie** [comment]
@DanielaVasco I opened a new issue #25

**Comment by DanielaVasco** [comment]
Dear Andrie,

I continue receiving the same error message when I call the function
dendro_data().

Thanks,
Daniela

**Comment by andrie** [comment]
Are you using the dev branch?  This isn't in master yet.

**Comment by DanielaVasco** [comment]
I am just calling the function directly.
Sorry, what is the "dev branch"?

Thanks

**Comment by andrie** [comment]
How do you install the package at the moment?

You have to install the development version from github using devtools, specifically the development branch (dev).

Use `devtools::install_github()` for this and set the `ref = "dev"` argument.

**Comment by DanielaVasco** [comment]
Thanks Andrie,

Now it is working :)
