### ISSUE TITLE
geom_text arguments from ggdendrogram

### ISSUE THREAD

**Issue by fawda123** [andrie/ggdendro#21]
The documentation for `ggendrogram` states that the ellipses argument passes additional parameters to `geom_text`.  This feature doesn't seem to be working, so may be a bug?

```r
library(ggplot2)
library(ggdendro)

hc <- hclust(dist(USArrests), "ave")
p <- ggdendrogram(hc, rotate=FALSE, colour = 'red')
print(p) # no color change

```

**Comment by talgalili** [comment]
As far as I know, ggdendro does not use geom_text. If you are interested in control over text color/size you can use ggdend from the dendextend package. See:
https://cran.r-project.org/web/packages/dendextend/vignettes/introduction.html#ggplot2-integration

**Comment by fawda123** [comment]
Okay, thanks Tal.  I'll see what I can do from the vignette.  

I just looked at the file for `ggdendrogram` and it does use `geom_text` on line 55: https://github.com/andrie/ggdendro/blob/master/R/ggdendrogram.R

So I guess I'm still curious why it doesn't correctly handle the additional arguments.

**Comment by talgalili** [comment]
Thanks for checking - it seems I was confused with regards to this.
It seems it doesn't work since geom_text would need to use your argument (however it seems it does not). 
Either way, I was inspired to built ggdend in dendextend from the ggdendro work, and tried to make sure to include all the features ggdendro has (for dendrograms). If you think it is missing something - please let me know.

With regards,
Tal
