### ISSUE TITLE
Node stack overflow error in dendro_data

### ISSUE THREAD

**Issue by GuptaPriyanshu** [andrie/ggdendro#27]
Hi,

We are trying to plot dendrogram but unfortunately for some cases we are getting error in dendro_data function.

**hcdata <- dendro_data(hc, type="rectangle")**

Error in : node stack overflow
No stack trace available

Is there any way i can get rid of this error ?

Thanks,
Priyanshu

**Comment by andrie** [comment]
Please provide a reproducible example

**Comment by GuptaPriyanshu** [comment]
Hi ,

I have attached two sample files.
1. mydata1.csv works fine
2. mydata.csv gives error as mentioned above

Below is the code in which i read data from csv file

**scaledData<-read.csv("mydata1.csv",header=TRUE)
dhc <<- hclust(dist(scaledData), method = "average")
ddata <- dendro_data(dhc, type = "rectangle")**



[files.zip](https://github.com/andrie/ggdendro/files/2251206/files.zip)

**Comment by andrie** [comment]
Yes, I can replicate the problem.  I'm not going to be able to investigate any time soon.

Meanwhile you can try:

* Use `plot(dhc)` from the package `rpart()`
* Reduce your data set (maybe using sampling) and then plot using `ggdendro`

**Comment by thommohr** [comment]
The issue is still present when dealing with large dendrograms .....

**Comment by thommohr** [comment]
Hi, the issue still persists. It is extremely problematic when analyzing genetic data. Any chance it will be resolved soon ?

best,
Thomas

**Comment by andrie** [comment]
Do you get the same problem when using `rpart()` ?

**Comment by thommohr** [comment]
Sorry for the late reply, was very busy the last months. 

Quote: "Do you get the same problem when using rpart() ?"

I am not sure how to use rpart, but will look it up.

The problem is with co-expression network analyses, which typically result in dendrograms with 20.000+ leafs. Plotting the dendrogram with the normal plotting fuction is not a problem. However, I would love to integrate this into ggplot2 since I think this is a really great way to write papers.

**Comment by thommohr** [comment]
The issue is sill present in the latest release.I tried to plot a dendrogram generated by hclust with roughly 14695. I think the problem lies with a recursive function call within the as.dendrogram function.

**Comment by andrie** [comment]
Correct.  Since `ggdendro` doesn't do this compuation, but `rpart` does, this can't be fixed in `ggdendro`, really.  If you can demonstrate that `rpart` can do the computation but `ggdendro` can not, then I will investigate.

**Comment by andrie** [comment]
Sorry, I said `rpart` but of course you're using `hclust`.   In either case, the dendogram itself is generated by `as.dendrogram` in the stats package (part of base R).  If the base `stats` package is causing the problem, then `ggdendro` can not help you solve this, unfortunately.

Still, if you can find a solution using base R, this will demonstrate that the problem lies with `ggdendro`, and then I can investigate.

**Comment by thommohr** [comment]
Hi Andrie,

thanks for the prompt reply. Plotting the dendrogram with plot(hclustobject) is no problem at all. The function as.dendrogram works fine.

The culprit is the gg.plotNode function defined in the dendrogram_data function, I believe the recursive function call in line 282-285 of dendrogram.R

I hope that helps. Dendrograms of this size are nothing unusual in -omics data analysis, and it would be really nice to be able to plot dendrograms in ggplot. Plotting them using plot and reimporting the png file is - let's put it this way - suboptimal.

best, and thanks for your work !
Thomas

**Comment by ljwharbers** [comment]
Hi,

I'm running into the same issue. Is there any update on this issue?

Thanks a lot for your work!
Luuk

**Comment by andrewGhazi** [comment]
Hi there, just wanted to bump this issue as I've had problems with it as well. As thommor pointed out, the issue is caused by [this recursive call](https://github.com/andrie/ggdendro/blob/b75c06e11698a5deda638adc556f0e263b38d5a7/R/dendrogram.R#L293) to `gg.plotNode()`. 

Attached is a plot from `plot.hclust()` on an hclust result that causes the issue. Not a very interesting tree, but I'm using `dendro_data()` in a package that sometimes runs into examples like this (which is also why I want the lighter dependency footprint of ggdendro vs dendextend). Many leaves branch off from the same node at height = 0, so I think what's going on in this case is the recursive function adds a a new layer to the call stack for each leaf until it hits the limit. The final error message is:
```
> ggdendro::dendro_data(path_clust)
Error: node stack overflow
Error during wrapup: node stack overflow
Error: no more error handlers available (recursive errors?); invoking 'abort' restart
```

 Github doesn't allow uploading RData files to issues, so I ran the hclust result through `dput()` and put it into a txt file.

I appreciate any help, ggdendro is awesome!


[path_clust_dput.txt](https://github.com/andrie/ggdendro/files/10493161/path_clust_dput.txt)

![dendro_data_clust](https://user-images.githubusercontent.com/6763470/214380087-5e9921b7-44a7-4717-9125-8d052dbab612.png)

**Comment by crotoc** [comment]
This problem happens because there is too much identical branches and the recursive function invoked overflow the limit. A work around is adding a small random value to the original matrix to make sure their are not so many identical rows.

https://support.bioconductor.org/p/125023/

**Comment by andrie** [comment]
I have pushed a fix to the main branch on github.  Please can you install the latest version from github and let me know if this works on your real world data.

Using the example provided by @GuptaPriyanshu , I now get this plot output:

![image](https://github.com/andrie/ggdendro/assets/479998/1e951e11-1d7f-4091-bba8-51d3dbd2e557)

**Comment by andrie** [comment]
Re-opening, since there are some performance optimisation gains possible.

**Comment by andrie** [comment]
The example now runs in ~1.5 seconds on my machine.

**Comment by andrie** [comment]
I am delighted to finally close this bug, after 6 years.  Version 0.2.0 was accepted by CRAN on 2023-02-24.
