### ISSUE TITLE
Plotting problems when converting from data.tree

### ISSUE THREAD

**Issue by jrijn** [andrie/ggdendro#31]
Hi Andrie, 

Thanks for a great package!
I am trying to convert a data.tree structure, which holds splitting events over time, to a ggdendrogram to control plotting parameters. However, I run into problems with centering the branches when converting from a data.tree. 

An example: 

```{r}
library(data.tree)
library(ggdendro)

df <- data.frame(from = c(1,2,3,3,4,4),
                 to = c(2,3,4,5,6,7))

tree <- FromDataFrameNetwork(df)
plot(tree) # This is fine
plot(as.dendrogram(tree)) # This is not fine
plot(as.dendrogram(tree), center = TRUE) # This is great

ggdendrogram(as.dendrogram(tree)) # Here is where I run into trouble
```

Do you know if this can currently be solved?

Thanks in advance,

Jorik

**Comment by andrie** [comment]
I just ran your code, and it worked fine (see reprex below).

It is possible that your issue was inadvertently fixed in a recent commit that's now available on github.

I'm closing this issue.  Please re-open with additional information if this is still a problem.

``` r
library(data.tree)
library(ggdendro)

df <- data.frame(from = c(1,2,3,3,4,4),
                 to = c(2,3,4,5,6,7))

tree <- FromDataFrameNetwork(df)
ggdendrogram(as.dendrogram(tree))
```

![](https://i.imgur.com/2S3m36F.png)

<sup>Created on 2023-09-30 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
